FROM python:3.12.3-slim-bookworm

ENV DEBIAN_FRONTEND=noninteractive \
    PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    bash ca-certificates procps tini wget && \
    rm -rf /var/lib/apt/lists/* && \
    python -m pip install --upgrade pip && \
    python -m pip install 'ray[default]==2.52.1'

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["bash"]
